# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  aws-cli-cred-setup:
    executor: aws-cli/default
    steps:
      - aws-cli/setup:
          aws-access-key-id: AWS_ACCESS_KEY
          aws-secret-access-key: AWS_ACCESS_SECRET
          aws-session-token: AWS_SESSION_TOKEN
          aws-region: AWS_REGION_NAME
  create-infrastructure: 
    docker: 
      - image: amazon/aws-cli
    steps:
      - checkout
      - run: 
          name: Create Cloudformation Stack
          command: |
            aws cloudformation deploy --template-file template.yml --stack-name mystack-${CIRCLE_WORKFLOW_ID:0:5} --region us-east-1

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  create-infrastructure-workflow: 
    jobs: 
      - create-infrastructure:
          requires: 
            - aws-cli-cred-setup
      - aws-cli-cred-setup
    